abc.local. 120 IN A 192.168.37.137
137.37.168.192.in-addr.arpa. 60 IN PTR abc.local.

_ssh._tcp.local. 60 IN PTR abc._ssh._tcp.local.

abc._ssh._tcp.local. 60 IN SRV 0 0 22 abc.local.

abc._ssh._tcp.local. 60 IN TXT ""

_services._dns-sd._udp.local. 60 IN PTR _ssh._tcp.local.
